import type { Metadata } from "next";
import "./globals.css";
import EmotionCacheProvider from "./EmotionCacheProvider";

export const metadata: Metadata = {
  title: "모하모 프론트",
  description: "Generated by create mohamo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {/* Emotion 캐싱 */}
        <EmotionCacheProvider>{children}</EmotionCacheProvider>
      </body>
    </html>
  );
}
